Adding Team Processing chapter
delftswa2017/desosa2017 pull request #18
Opened 2017-04-03 21:07 UTC by bergvel1

2017-04-15 17:15 UTC, sandervdo requested changes
Please rename `team-processing` to `processing`.

As per feedback in your private repository your chapter can be included in the book. You are free to make more improvements before having it merged. Please indicate whether you want to include or exclude your chapter in the book. 😄

2017-04-18 14:45 UTC, bergvel1 commented
Hey @sandervdo !

We've made the changes you requested, and wanted to let you know that we would like to have our chapter included in the book. Please let us know if there is anything else we can do. 🙂

2017-04-18 20:49 UTC, sandervdo approved these changes

2017-04-18 20:52 UTC, merged

2017-04-18 20:53 UTC, sandervdo commented
Thanks. 👍 It has been merged into the book. 😄